#!/bin/sh
# /etc/X11/xinit/xinitrc

# global xinitrc file, used by all X sessions started by xinit (startx)
# invoke global X session script
if [ -r "{{homeDirectory}}/.xsession" ]; then
  . "{{homeDirectory}}/.xsession"
else
  . /etc/X11/Xsession
fi

export DISPLAY=:0
export XAUTHORITY="{{homeDirectory}}/.Xauthority"
/usr/bin/dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

