#!/bin/sh
# /etc/X11/xinit/xinitrc

# global xinitrc file, used by all X sessions started by xinit (startx)
# invoke global X session script
if [ -r "{{homeDirectory}}/.xsession" ]; then
  . "{{homeDirectory}}/.xsession"
else
  . /etc/X11/Xsession
fi

export DISPLAY=:0
export XAUTHORITY="{{homeDirectory}}/.Xauthority"
export NO_AT_BRIDGE=1
export XDG_DATA_DIRS="{{homeDirectory}}/.local/share:{{homeDirectory}}/.nix-profile/share:{{homeDirectory}}/.local/state/nix/profiles/profile/share:/var/lib/flatpak/exports/share:''${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
/usr/bin/dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY XDG_DATA_DIRS

