# The left offset for shadows, in pixels.
#
# Default: -15
shadow-offset-x = -2;

# The top offset for shadows, in pixels.
#
# Default: -15
shadow-offset-y = -2;

# Fading mechanism treats a new workspace
# as a transparent window, causing focus
# issues or a "flash" of the desktop background
fade-exclude = [
  "class_g = 'i3-frame'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];
