#!/bin/sh
# /etc/X11/xinit/xinitrc

# global xinitrc file, used by all X sessions started by xinit (startx)
# invoke global X session script
if [ -r "{{homeDirectory}}/.xsession" ]; then
  . "{{homeDirectory}}/.xsession"
else
  . /etc/X11/Xsession
fi

export DISPLAY=:0
export XAUTHORITY="{{homeDirectory}}/.Xauthority"
/usr/bin/dbus-update-activation-environment --systemd DISPLAY XAUTHORITY

# VMware
if command -v vmware-user-suid-wrapper >/dev/null; then
  /usr/bin/vmware-user-suid-wrapper &
fi

