#!/bin/sh

insidecolor=00000000
ringcolor=ffffffff
keyhlcolor=d23c3dff
bshlcolor=d23c3dff
separatorcolor=00000000
insidevercolor=00000000
insidewrongcolor=d23c3dff
ringvercolor=ffffffff
ringwrongcolor=ffffffff
verifcolor=ffffffff
timecolor=ffffffff
datecolor=ffffffff
loginbox=00000066
font="sans-serif"
locktext='Type password to unlock...'

{{i3lockBin}}/i3lock \
    -n -e --color=101014 \
    --clock --time-pos='x+110:h-70' \
    --date-align 1 --date-str "$locktext" --date-pos='x+43:h-45' \
    --inside-color="$insidecolor" --ring-color="$ringcolor" --line-uses-inside \
    --keyhl-color="$keyhlcolor" --bshl-color="$bshlcolor" --separator-color="$separatorcolor" \
    --insidever-color="$insidevercolor" --insidewrong-color="$insidewrongcolor" \
    --ringver-color="$ringvercolor" --ringwrong-color="$ringwrongcolor" --ind-pos='x+280:h-70' \
    --radius=20 --ring-width=4 \
    --verif-text='' --wrong-text='' --noinput-text='' \
    --verif-color="$verifcolor" --time-color="$timecolor" --date-color="$datecolor" \
    --time-font="$font" --date-font="$font" --layout-font="$font" \
    --verif-font="$font" --wrong-font="$font" \
    --force-clock --pass-media-keys
